### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by DineshRajanT** [anish9/Image-Auto-Enhancer#1]
What is that v1.h5 model?Trained on which dataset?

**Comment by anish9** [comment]
@DineshRajanT  v1.h5 was trained on synthetic dataset

**Comment by DineshRajanT** [comment]
Wanna know more about the training process ....to train my own model.

**Comment by anish9** [comment]
base idea is SRGAN  @DineshRajanT

**Comment by anish9** [comment]
I am closing this issue for now
